export const state = () => ({
  selected: null,
  selectedBathymetry: '',
  selectedAltimetrySatellites: [],
  selectedAltimetryDates: [],
  selectedAltimetryVariable: null,
  altimetryLoadedGJs: [], // --- [{satellite:'', date:'', gj:''}, ...]
  altimetryShownGJs: [], // --- Stores altimetry gj's already shown on the map.  Used for finding min/max in colorbar.
  loadingAltimetry: false,
  altimetryAvailSatDates: {},

  // --- Keep track of last selected date and time between models
  interDate: null,
  interTime: null,

  bathymetries: {
    field: 'Bathymetry',
    show: true,
    longName: null,
    models: [
      {
        source: 'SRTM',
        modelDir: 'SRTM',
        longName: '',
        link: '',
        region: 'G',
        maxZoom: 7,
        imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
        min: -10900,
        max: 0,
        // colorbar: {
        //   labels: [
        //     { location: 0, label: '0' },
        //     { location: 0.0909, label: '1000' },
        //     { location: 0.1818, label: '2000' },
        //     { location: 0.2727, label: '3000' },
        //     { location: 0.3636, label: '4000' },
        //     { location: 0.4545, label: '5000' },
        //     { location: 0.5454, label: '6000' },
        //     { location: 0.6363, label: '7000' },
        //     { location: 0.7272, label: '8000' },
        //     { location: 0.8181, label: '9000' },
        //     { location: 0.909, label: '10000' },
        //     { location: 1, label: '11000' },
        //   ],
        //   colormap: [
        //     {
        //       minValue: -11000,
        //       maxValue: -10000,
        //       minColor: [40, 26, 44],
        //       maxColor: [54, 43, 77],
        //     },
        //     {
        //       minValue: -10000,
        //       maxValue: -9000,
        //       minColor: [54, 43, 77],
        //       maxColor: [64, 60, 115],
        //     },
        //     {
        //       minValue: -9000,
        //       maxValue: -8000,
        //       minColor: [64, 60, 115],
        //       maxColor: [63, 84, 144],
        //     },
        //     {
        //       minValue: -8000,
        //       maxValue: -7000,
        //       minColor: [63, 84, 144],
        //       maxColor: [63, 108, 150],
        //     },
        //     {
        //       minValue: -7000,
        //       maxValue: -6000,
        //       minColor: [63, 108, 150],
        //       maxColor: [68, 131, 155],
        //     },
        //     {
        //       minValue: -6000,
        //       maxValue: -5000,
        //       minColor: [68, 131, 155],
        //       maxColor: [76, 154, 160],
        //     },
        //     {
        //       minValue: -5000,
        //       maxValue: -4000,
        //       minColor: [76, 154, 160],
        //       maxColor: [87, 177, 164],
        //     },
        //     {
        //       minValue: -4000,
        //       maxValue: -3000,
        //       minColor: [87, 177, 164],
        //       maxColor: [110, 200, 163],
        //     },
        //     {
        //       minValue: -3000,
        //       maxValue: -2000,
        //       minColor: [110, 200, 163],
        //       maxColor: [156, 220, 165],
        //     },
        //     {
        //       minValue: -2000,
        //       maxValue: -1000,
        //       minColor: [156, 220, 165],
        //       maxColor: [206, 236, 179],
        //     },
        //     {
        //       minValue: -1000,
        //       maxValue: 0,
        //       minColor: [206, 236, 179],
        //       maxColor: [253, 254, 204],
        //     },
        //   ],
        // },
        availContourLevels: [].concat(
          [...Array(99).keys()].map((k) => -10 * k), // --- 0 ... -990 , step 10
          [...Array(99).keys()].map((k) => -20 * k - 1000), // --- -1000 ... -2980 , step 20
          [...Array(19).keys()].map((k) => -50 * k - 3000), // --- -3000 ... -4950 , step 50
          [...Array(60).keys()].map((k) => -100 * k - 5000) // --- -5000 ... -11000 , step 100
        ),
        // unit: 'm',
      },
      // {
      //   source: 'GEBCO',
      //   modelDir: 'GEBCO',
      //   longName: '',
      //   region: 'G',
      //   imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
      //   min: -11000,
      //   max: 0,
      //   // colorbar: {
      //   //   hasColorbar: true,
      //   //   labels: [
      //   //     { location: 0, label: '0' },
      //   //     { location: 0.0909, label: '1000' },
      //   //     { location: 0.1818, label: '2000' },
      //   //     { location: 0.2727, label: '3000' },
      //   //     { location: 0.3636, label: '4000' },
      //   //     { location: 0.4545, label: '5000' },
      //   //     { location: 0.5454, label: '6000' },
      //   //     { location: 0.6363, label: '7000' },
      //   //     { location: 0.7272, label: '8000' },
      //   //     { location: 0.8181, label: '9000' },
      //   //     { location: 0.909, label: '10000' },
      //   //     { location: 1, label: '11000' },
      //   //   ],
      //   //   colormap: [
      //   //     {
      //   //       minValue: -11000,
      //   //       maxValue: -10000,
      //   //       minColor: [40, 26, 44],
      //   //       maxColor: [54, 43, 77],
      //   //     },
      //   //     {
      //   //       minValue: -10000,
      //   //       maxValue: -9000,
      //   //       minColor: [54, 43, 77],
      //   //       maxColor: [64, 60, 115],
      //   //     },
      //   //     {
      //   //       minValue: -9000,
      //   //       maxValue: -8000,
      //   //       minColor: [64, 60, 115],
      //   //       maxColor: [63, 84, 144],
      //   //     },
      //   //     {
      //   //       minValue: -8000,
      //   //       maxValue: -7000,
      //   //       minColor: [63, 84, 144],
      //   //       maxColor: [63, 108, 150],
      //   //     },
      //   //     {
      //   //       minValue: -7000,
      //   //       maxValue: -6000,
      //   //       minColor: [63, 108, 150],
      //   //       maxColor: [68, 131, 155],
      //   //     },
      //   //     {
      //   //       minValue: -6000,
      //   //       maxValue: -5000,
      //   //       minColor: [68, 131, 155],
      //   //       maxColor: [76, 154, 160],
      //   //     },
      //   //     {
      //   //       minValue: -5000,
      //   //       maxValue: -4000,
      //   //       minColor: [76, 154, 160],
      //   //       maxColor: [87, 177, 164],
      //   //     },
      //   //     {
      //   //       minValue: -4000,
      //   //       maxValue: -3000,
      //   //       minColor: [87, 177, 164],
      //   //       maxColor: [110, 200, 163],
      //   //     },
      //   //     {
      //   //       minValue: -3000,
      //   //       maxValue: -2000,
      //   //       minColor: [110, 200, 163],
      //   //       maxColor: [156, 220, 165],
      //   //     },
      //   //     {
      //   //       minValue: -2000,
      //   //       maxValue: -1000,
      //   //       minColor: [156, 220, 165],
      //   //       maxColor: [206, 236, 179],
      //   //     },
      //   //     {
      //   //       minValue: -1000,
      //   //       maxValue: 0,
      //   //       minColor: [206, 236, 179],
      //   //       maxColor: [253, 254, 204],
      //   //     },
      //   //   ],
      //   // },
      //   // unit: 'm',
      // },
      // {
      //   source: 'NONNA',
      //   modelDir: 'NONNA',
      //   longName: '',
      //   region: 'R',
      //   imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
      //   // min: -500,
      //   // max: 0,
      //   // colorbar: {
      //   //   hasColorbar: true,
      //   //   labels: [
      //   //     { location: 0, label: '0' },
      //   //     { location: 0.1, label: '100' },
      //   //     { location: 0.2, label: '200' },
      //   //     { location: 0.3, label: '300' },
      //   //     { location: 0.4, label: '400' },
      //   //     { location: 0.5, label: '500' },
      //   //     { location: 0.75, label: '750' },
      //   //     { location: 1, label: '1000+' },
      //   //   ],
      //   //   colormap: [
      //   //     {
      //   //       minValue: -1000,
      //   //       maxValue: -750,
      //   //       minColor: [102, 0, 102],
      //   //       maxColor: [153, 102, 255],
      //   //     },
      //   //     {
      //   //       minValue: -750,
      //   //       maxValue: -500,
      //   //       minColor: [153, 102, 255],
      //   //       maxColor: [51, 102, 255],
      //   //     },
      //   //     {
      //   //       minValue: -500,
      //   //       maxValue: -400,
      //   //       minColor: [51, 102, 255],
      //   //       maxColor: [51, 102, 255],
      //   //     },
      //   //     {
      //   //       minValue: -400,
      //   //       maxValue: -300,
      //   //       minColor: [51, 102, 255],
      //   //       maxColor: [51, 204, 204],
      //   //     },
      //   //     {
      //   //       minValue: -300,
      //   //       maxValue: -200,
      //   //       minColor: [51, 204, 204],
      //   //       maxColor: [51, 204, 51],
      //   //     },
      //   //     {
      //   //       minValue: -200,
      //   //       maxValue: -100,
      //   //       minColor: [51, 204, 51],
      //   //       maxColor: [255, 255, 0],
      //   //     },
      //   //     {
      //   //       minValue: -100,
      //   //       maxValue: 0,
      //   //       minColor: [255, 255, 0],
      //   //       maxColor: [255, 51, 0],
      //   //     },
      //   //   ],
      //   // },
      //   // availContourLevels: [...Array(508).keys()].map((k) => -10 * k), // --- Array from 0 to -5080, with step = 10
      //   // unit: 'm',
      // },
      // {
      //   source: 'NOAA',
      //   modelDir: 'NOAA',
      //   region: 'R',
      //   colorbar: {
      //     hasColorbar: true
      //   },
      //   availContourLevels: [...Array(508).keys()].map(k => -10 * k), // --- Array from 0 to -5080, with step = 10
      //   unit: 'm'
      // }
      {
        source: 'greatLakes',
        modelDir: 'greatLakes',
        longName:
          'NOAA was engaged in a program to compile Great Lakes bathymetric data and make them readily available to the public. This program was managed by NCEI and relied on the cooperation of NOAA/Great Lakes Environmental Research Laboratory, NOAA/National Ocean Service, the Canadian Hydrographic Service, other agencies, and academic laboratories.',
        link: 'https://www.ngdc.noaa.gov/mgg/greatlakes/',
        region: 'R',
        maxZoom: 14,
        imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
        min: -390,
        max: 0,
        availContourLevels: [...Array(38).keys()].map((k) => -10 * k), // --- 0 ... -380 , step 10
      },
    ],
    colorbar: {
      step: 1,
      minOrg: 0,
      toFixed: 0,
      colormapOrg: [
        {
          value: 0,
          color: '#fefecc',
        },
        {
          value: 1000,
          color: '#9fdda6',
        },
        {
          value: 2000,
          color: '#59b5a4',
        },
        {
          value: 4000,
          color: '#46879c',
        },
        {
          value: 6000,
          color: '#3e5992',
        },
        {
          value: 8000,
          color: '#3a3058',
        },
        {
          value: 11000,
          color: '#271a2c',
        },
      ],
      colormap: [
        {
          value: 0,
          color: '#fefecc',
        },
        {
          value: 1000,
          color: '#9fdda6',
        },
        {
          value: 2000,
          color: '#59b5a4',
        },
        {
          value: 4000,
          color: '#46879c',
        },
        {
          value: 6000,
          color: '#3e5992',
        },
        {
          value: 8000,
          color: '#3a3058',
        },
        {
          value: 11000,
          color: '#271a2c',
        },
      ],
    },
    unit: 'm',
  },

  categories: [
    {
      name: 'Currents',
      show: true,
      atmosphere: false,
      longName: null,
      fields: [
        {
          name: 'Currents',
          models: [
            {
              category: 'Currents',
              field: 'Currents',
              subProducts: { hasSub: false },
              modelDir: 'HYCOM',
              btnText: 'HYCOM',
              longName: 'Hybrid Coordinate Ocean Model',
              link: 'https://www.hycom.org/',
              region: 'G',
              depthProperties: {
                hasDepth: true,
                iDepth: 0,
                // depthValues: [
                //   0, 2, 4, 6, 8, 10, 12, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70,
                //   80, 90, 100, 125, 150, 200, 250, 300, 350, 400, 500, 600, 700,
                //   800, 900, 1000, 1250, 1500, 2000, 2500, 3000, 4000, 5000,
                // ],
                depthLabels: ['Surface', '20 - 200 m', '50 - 1000 m'],
                depthValues: ['00000-00010', '00020-00200', '00050-01000'],
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 85 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
            {
              category: 'Currents',
              field: 'Currents',
              subProducts: { hasSub: false },
              modelDir: 'RIOPS',
              btnText: 'RIOPS',
              longName: 'Regional Ice Ocean Prediction System',
              link: 'https://eccc-msc.github.io/open-data/msc-data/nwp_riops/readme_riops-datamart-alpha_en/',
              region: 'R',
              depthProperties: {
                hasDepth: true,
                iDepth: 0,
                depthLabels: ['Surface', '20 - 200 m', '50 - 1000 m'],
                // depthLabels: [
                //     '1.5 - 2.0 km',
                //     '1.0 - 1.5 km',
                //     '500 - 1000 m',
                //     '200 - 500 m',
                //     '100 - 200 m',
                //     '50 - 100 m',
                //     '10 - 50 m',
                //     'Surface',
                // ],
                depthValues: ['00000-00010', '00020-00200', '00050-01000'],
                // depthValues: [
                //     '1500-2000',
                //     '1000-1500',
                //     '0500-1000',
                //     '0200-0500',
                //     '0100-0200',
                //     '0050-0100',
                //     '0010-0050',
                //     '0000-0010',
                // ],
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -85, maxLat: 85 },
              imgBndsZoomed: false,
              min: 0,
              max: 3,
              availDateTimes: [],
              hasDateTime: true,
            },
            {
              category: 'Currents',
              field: 'Currents',
              subProducts: { hasSub: false },
              modelDir: 'CMC',
              btnText: 'CMC',
              longName: 'Global Environmental Multiscale Model',
              link: 'https://en.wikipedia.org/wiki/Global_Environmental_Multiscale_Model',
              region: 'R',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -71, maxLon: -56, minLat: 45.5, maxLat: 52 },
              imgBndsZoomed: false,
              min: 0,
              max: 1,
              availDateTimes: [],
              hasDateTime: true,
            },
            // {
            //   field: 'Currents',
            //   modelDir: 'WMOP',
            //   btnText: 'WMOP',
            //   longName:
            //     'Western Mediterranean OPerational forecasting system (surface)',
            //   depthProperties: {
            //     hasDepth: false
            //   },
            //   imgBnds: { minLon: -5.8, maxLon: 9.2, minLat: 35, maxLat: 44.5 },
            //   imgBndsZoomed: false,
            //   min: 0,
            //   max: 1.5,
            //   availDateTimes: [],
            //   hasHighRes: false,
            //   colorbar: {
            //     hasColorbar: false
            //   },
            //   unit: '<sup>m</sup>&frasl;<sub>s</sub>'
            // },
            // {
            //   field: 'Currents',
            //   modelDir: 'CMEMS',
            //   btnText: 'CMEMS',
            //   longName: 'Copernicus Monitoring Environment Marine Service',
            //   depthProperties: {
            //     hasDepth: false
            //     // iDepth: 14,
            //     // depthLabels: [
            //     //     '399 m',
            //     //     '304 m',
            //     //     '250 m',
            //     //     '203 m',
            //     //     '153 m',
            //     //     '98 m',
            //     //     '73 m',
            //     //     '51 m',
            //     //     '30 m',
            //     //     '19 m',
            //     //     '11 m',
            //     //     '8 m',
            //     //     '5 m',
            //     //     '3 m',
            //     //     '1 m',
            //     // ],
            //     // depthValues: [
            //     //     '0399',
            //     //     '0304',
            //     //     '0250',
            //     //     '0203',
            //     //     '0153',
            //     //     '0098',
            //     //     '0073',
            //     //     '0051',
            //     //     '0030',
            //     //     '0019',
            //     //     '0011',
            //     //     '0008',
            //     //     '0005',
            //     //     '0003',
            //     //     '0001',
            //     // ],
            //   },
            //   imgBnds: {
            //     minLon: -17.2917,
            //     maxLon: 36.2917,
            //     minLat: 30.1875,
            //     maxLat: 45.9792
            //   },
            //   imgBndsZoomed: false,
            //   min: 0,
            //   max: 1.5,
            //   availDateTimes: [],
            //   hasHighRes: false,
            //   colorbar: {
            //     hasColorbar: false
            //   },
            //   unit: '<sup>m</sup>&frasl;<sub>s</sub>'
            // },
            {
              category: 'Currents',
              field: 'Currents',
              modelDir: 'Doppio',
              btnText: 'Doppio',
              longName: '',
              link: 'https://gmd.copernicus.org/articles/13/3709/2020/',
              region: 'R',
              depthProperties: {
                hasDepth: true,
                iDepth: 0,
                depthLabels: ['avgDepth'],
                depthValues: ['avgDepth'],
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -85, maxLat: 85 },
              imgBndsZoomed: false,
              min: 0,
              max: 3,
              availDateTimes: [],
              hasDateTime: true,
            },
            {
              category: 'Currents',
              field: 'Currents',
              modelDir: 'Barents',
              btnText: 'Barents',
              longName: '',
              link: 'https://www.met.no/hav-og-nordomrader-landing',
              region: 'R',
              depthProperties: {
                hasDepth: true,
                iDepth: 0,
                depthLabels: ['Surface', '20 - 200 m', '50 - 1000 m'],
                depthValues: ['surface', '0020-0200', '0200-1000'],
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -85, maxLat: 85 },
              imgBndsZoomed: false,
              min: 0,
              max: Math.sqrt(2),
              availDateTimes: [],
              hasDateTime: true,
            },
            {
              category: 'Currents',
              field: 'Currents',
              subProducts: { hasSub: false },
              modelDir: 'NorKyst800m',
              btnText: 'NorKyst',
              longName:
                'Norkyst-800 is used as the main forecast tool for ocean forecasting at the coast of Norway.',
              link: 'https://ocean.met.no/models',
              region: 'R',
              depthProperties: {
                hasDepth: true,
                iDepth: 0,
                depthLabels: ['Surface', '20 - 200 m', '50 - 1000 m'],
                depthValues: ['surface', '0020-0200', '0200-1000'],
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -85, maxLat: 85 },
              imgBndsZoomed: false,
              min: 0,
              max: 1.5 * Math.sqrt(2),
              availDateTimes: [],
              hasDateTime: true,
            },
          ],
          colorbar: {
            step: 0.01,
            minOrg: -3,
            toFixed: 1,
            colormapOrg: [
              {
                value: 0,
                color: '#cc00cc',
              },
              {
                value: 0.5,
                color: '#0066cc',
              },
              {
                value: 1,
                color: '#009933',
              },
              {
                value: 1.5,
                color: '#ffff00',
              },
              {
                value: 2,
                color: '#ff0000',
              },
              {
                value: 2.5,
                color: '#ffcccc',
              },
            ],
            colormap: [
              {
                value: 0,
                color: '#cc00cc',
              },
              {
                value: 0.5,
                color: '#0066cc',
              },
              {
                value: 1,
                color: '#009933',
              },
              {
                value: 1.5,
                color: '#ffff00',
              },
              {
                value: 2,
                color: '#ff0000',
              },
              {
                value: 2.5,
                color: '#ffcccc',
              },
            ],
          },
          unit: '<sup>m</sup>&frasl;<sub>s</sub>',
          icon: 'mdi-sync',
          hasSetting: true,
        },
      ],
    },
    {
      name: 'SST',
      show: true,
      atmosphere: false,
      longName: 'Sea Surface Temperature',
      fields: [
        {
          name: 'SST',
          models: [
            {
              category: 'SST',
              field: 'SST',
              subProducts: { hasSub: false },
              modelDir: 'JPLMUR41',
              btnText: 'JPLMUR',
              longName:
                'Level 4 MUR Global Foundation Sea Surface Temperature Analysis (v4.1)',
              link: 'https://podaac.jpl.nasa.gov/dataset/MUR-JPL-L4-GLOB-v4.1',
              region: 'G',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
            {
              category: 'SST',
              field: 'SST',
              subProducts: { hasSub: false },
              modelDir: 'Coraltemp',
              btnText: 'Coraltemp',
              longName:
                'Daily Global 5km Satellite Coral Bleaching Heat Stress Monitoring (v3.1)',
              link: 'https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.nodc:CRW-5km-HeatStressProducts',
              region: 'G',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
            {
              category: 'SST',
              field: 'SST',
              subProducts: { hasSub: false },
              modelDir: 'HYCOM',
              btnText: 'HYCOM',
              longName: 'Hybrid Coordinate Ocean Model',
              link: 'https://www.hycom.org/',
              region: 'G',
              depthProperties: {
                hasDepth: false,
                iDepth: 39,
                depthValues: [
                  5000, 4000, 3000, 2500, 2000, 1500, 1250, 1000, 900, 800, 700,
                  600, 500, 400, 350, 300, 250, 200, 150, 125, 100, 90, 80, 70,
                  60, 50, 45, 40, 35, 30, 25, 20, 15, 12, 10, 8, 6, 4, 2, 0,
                ],
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
            {
              category: 'SST',
              field: 'SST',
              subProducts: { hasSub: false },
              modelDir: 'RIOPS',
              btnText: 'RIOPS',
              longName: 'Regional Ice Ocean Prediction System',
              link: 'https://eccc-msc.github.io/open-data/msc-data/nwp_riops/readme_riops-datamart-alpha_en/',
              region: 'R',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
            {
              category: 'SST',
              field: 'SST',
              subProducts: { hasSub: false },
              modelDir: 'CIOPS',
              btnText: 'CIOPS',
              longName: '',
              link: '',
              region: 'R',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
            {
              category: 'SST',
              field: 'SST',
              subProducts: { hasSub: false },
              modelDir: 'Barents',
              btnText: 'Barents',
              longName: '',
              link: 'https://www.met.no/hav-og-nordomrader-landing',
              region: 'G',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
            {
              category: 'SST',
              field: 'SST',
              subProducts: { hasSub: false },
              modelDir: 'GOES16',
              btnText: 'GOES16',
              longName: 'GOES16 Hourly Sea Surface Temperature Fields',
              link: 'https://cwcgom.aoml.noaa.gov/erddap/info/goes16SSThourly/index.html',
              region: 'G',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
            // {
            //   field: 'SST',
            //   modelDir: 'CMC',
            //   btnText: 'CMC',
            //   longName: '',
            //   depthProperties: {
            //     hasDepth: false
            //   },
            //   imgBnds: { minLon: -71, maxLon: -56, minLat: 45.5, maxLat: 52 },
            //   imgBndsZoomed: false,
            //   availDateTimes: [],
            // }
          ],
          colorbar: {
            hasColorbar: true,
            step: 0.1,
            minOrg: -2,
            toFixed: 0,
            colormapOrg: [
              {
                value: -2,
                color: '#cc00cc',
              },
              {
                value: 0,
                color: '#ff99ff',
              },
              {
                value: 0.1,
                color: '#0066cc',
              },
              {
                value: 10,
                color: '#66ffcc',
              },
              {
                value: 10.1,
                color: '#009933',
              },
              {
                value: 20,
                color: '#ccff66',
              },
              {
                value: 20.1,
                color: '#ffff00',
              },
              {
                value: 30,
                color: '#ff9933',
              },
              {
                value: 30.1,
                color: '#ff0000',
              },
              {
                value: 35,
                color: '#ffcccc',
              },
            ],
            colormap: [
              {
                value: -2,
                color: '#cc00cc',
              },
              {
                value: 0,
                color: '#ff99ff',
              },
              {
                value: 0.1,
                color: '#0066cc',
              },
              {
                value: 10,
                color: '#66ffcc',
              },
              {
                value: 10.1,
                color: '#009933',
              },
              {
                value: 20,
                color: '#ccff66',
              },
              {
                value: 20.1,
                color: '#ffff00',
              },
              {
                value: 30,
                color: '#ff9933',
              },
              {
                value: 30.1,
                color: '#ff0000',
              },
              {
                value: 35,
                color: '#ffcccc',
              },
            ],
          },
          unit: '&deg;C',
          icon: 'mdi-thermometer',
          hasSetting: false,
        },
      ],
    },
    {
      name: 'SSS',
      show: true,
      atmosphere: false,
      longName: 'Sea Surface Salinity',
      fields: [
        {
          name: 'SSS',
          models: [
            {
              category: 'SSS',
              field: 'SSS',
              subProducts: { hasSub: false },
              modelDir: 'HYCOM',
              btnText: 'HYCOM',
              longName: 'Hybrid Coordinate Ocean Model',
              link: 'https://www.hycom.org/',
              region: 'G',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
            {
              category: 'SSS',
              field: 'SSS',
              subProducts: { hasSub: false },
              modelDir: 'Barents',
              btnText: 'Barents',
              longName: '',
              link: 'https://www.met.no/hav-og-nordomrader-landing',
              region: 'G',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
          ],
          colorbar: {
            hasColorbar: true,
            step: 0.01,
            minOrg: 0,
            toFixed: 0,
            colormapOrg: [
              {
                value: 30,
                color: '#3333cc',
              },
              {
                value: 32,
                color: '#0099ff',
              },
              {
                value: 34,
                color: '#009933',
              },
              {
                value: 36,
                color: '#cccc00',
              },
              {
                value: 38,
                color: '#ff6600',
              },
            ],
            colormap: [
              {
                value: 30,
                color: '#3333cc',
              },
              {
                value: 32,
                color: '#0099ff',
              },
              {
                value: 34,
                color: '#009933',
              },
              {
                value: 36,
                color: '#cccc00',
              },
              {
                value: 38,
                color: '#ff6600',
              },
            ],
          },
          unit: 'psu',
          icon: 'mdi-shaker-outline',
          hasSetting: false,
        },
      ],
    },
    {
      name: 'SSD',
      show: true,
      atmosphere: false,
      longName: 'Sea Surface Density',
      fields: [
        {
          name: 'SSD',
          models: [
            {
              category: 'SSD',
              field: 'SSD',
              subProducts: { hasSub: false },
              modelDir: 'HYCOM',
              btnText: 'HYCOM',
              longName: 'Hybrid Coordinate Ocean Model',
              link: 'https://www.hycom.org/',
              region: 'G',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
            {
              category: 'SSD',
              field: 'SSD',
              subProducts: { hasSub: false },
              modelDir: 'Barents',
              btnText: 'Barents',
              longName: '',
              link: 'https://www.met.no/hav-og-nordomrader-landing',
              region: 'G',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
          ],
          colorbar: {
            hasColorbar: true,
            step: 0.1,
            minOrg: 900,
            toFixed: 0,
            colormapOrg: [
              {
                value: 1020,
                color: '#66ccff',
              },
              {
                value: 1022,
                color: '#0066ff',
              },
              {
                value: 1024,
                color: '#6666ff',
              },
              {
                value: 1026,
                color: '#6600ff',
              },
              {
                value: 1028,
                color: '#9900ff',
              },
              {
                value: 1030,
                color: '#660066',
              },
            ],
            colormap: [
              {
                value: 1020,
                color: '#66ccff',
              },
              {
                value: 1022,
                color: '#0066ff',
              },
              {
                value: 1024,
                color: '#6666ff',
              },
              {
                value: 1026,
                color: '#6600ff',
              },
              {
                value: 1028,
                color: '#9900ff',
              },
              {
                value: 1030,
                color: '#660066',
              },
            ],
          },
          unit: '<sup>kg</sup>&frasl;<sub>m<sup>3</sup></sub>',
          icon: 'mdi-format-line-weight',
          hasSetting: false,
        },
      ],
    },
    {
      name: 'MLD',
      show: true,
      atmosphere: false,
      longName: 'Mixed Layer Depth',
      fields: [
        {
          name: 'MLD',
          models: [
            {
              category: 'MLD',
              field: 'MLD',
              subProducts: { hasSub: false },
              modelDir: 'HYCOM',
              btnText: 'HYCOM',
              longName: 'Hybrid Coordinate Ocean Model',
              link: 'https://www.hycom.org/',
              region: 'G',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
            {
              category: 'MLD',
              field: 'MLD',
              subProducts: { hasSub: false },
              modelDir: 'RIOPS',
              btnText: 'RIOPS',
              longName: 'Regional Ice Ocean Prediction System',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
          ],
          colorbar: {
            hasColorbar: true,
            step: 1,
            minOrg: 0,
            toFixed: 0,
            colormapOrg: [
              {
                value: 0,
                color: '#cc00cc',
              },
              {
                value: 200,
                color: '#0066cc',
              },
              {
                value: 400,
                color: '#009933',
              },
              {
                value: 600,
                color: '#ffff00',
              },
              {
                value: 800,
                color: '#ff0000',
              },
              {
                value: 1000,
                color: '#ffcccc',
              },
            ],
            colormap: [
              {
                value: 0,
                color: '#cc00cc',
              },
              {
                value: 200,
                color: '#0066cc',
              },
              {
                value: 400,
                color: '#009933',
              },
              {
                value: 600,
                color: '#ffff00',
              },
              {
                value: 800,
                color: '#ff0000',
              },
              {
                value: 1000,
                color: '#ffcccc',
              },
            ],
          },
          unit: 'm',
          icon: 'mdi-account-circle',
          hasSetting: false,
        },
      ],
    },
    // {
    //   field: 'SWH',
    //   show: false,
    //   models: [
    //     {
    //       field: 'SWH',
    //       subProducts:{hasSub:true,fields:['SWH','Sea-state']},
    //       modelDir: 'CMC',
    //       btnText: 'GEM',
    //       longName: 'Global Environmental Multiscale Model',
    //       depthProperties: {
    //         hasDepth: false,
    //       },
    //       imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
    //       imgBndsZoomed: false,
    //       min: 0,
    //       max: 5,
    //       availDateTimes: [],
    //       hasDateTime: true,
    //       colorbar: {
    //         hasColorbar: true,
    //         labels: [
    //           { location: 0, label: '10+' },
    //           { location: 0.5, label: '5' },
    //           { location: 0.8, label: '2' },
    //           { location: 0.9, label: '1' },
    //           { location: 1, label: '0' },
    //         ],
    //         colormap: [
    //           {
    //             minValue: 0,
    //             maxValue: 2,
    //             minColor: [0, 51, 153],
    //             maxColor: [0, 255, 204],
    //           },
    //           {
    //             minValue: 2,
    //             maxValue: 4,
    //             minColor: [0, 255, 204],
    //             maxColor: [51, 204, 51],
    //           },
    //           {
    //             minValue: 4,
    //             maxValue: 6,
    //             minColor: [51, 204, 51],
    //             maxColor: [204, 204, 0],
    //           },
    //           {
    //             minValue: 6,
    //             maxValue: 8,
    //             minColor: [204, 204, 0],
    //             maxColor: [204, 0, 0],
    //           },
    //           {
    //             minValue: 8,
    //             maxValue: 10,
    //             minColor: [204, 0, 0],
    //             maxColor: [255, 204, 204],
    //           },
    //         ],
    //       },
    //       unit: 'm',
    //     },
    //   ],
    //   icon: 'mdi-waves',
    //   hasSetting: false,
    // },
    {
      name: 'Wave',
      show: true,
      atmosphere: false,
      longName: 'Wave Related Products',
      fields: [
        {
          name: 'SWH',
          longName: 'Sea Wave Height',
          models: [
            {
              category: 'Wave',
              field: 'SWH',
              modelDir: 'GFS',
              btnText: 'GFS',
              longName: 'Significant height of combined wind waves and swell',
              link: 'https://nomads.ncep.noaa.gov/',
              region: 'G',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
          ],
          colorbar: {
            step: 0.01,
            minOrg: 0,
            toFixed: 2,
            colormapOrg: [
              {
                value: 0,
                color: '#cc00cc',
              },
              {
                value: 1,
                color: '#0066cc',
              },
              {
                value: 2,
                color: '#009933',
              },
              {
                value: 5,
                color: '#ffff00',
              },
              {
                value: 10,
                color: '#ff0000',
              },
              {
                value: 20,
                color: '#ffcccc',
              },
            ],
            colormap: [
              {
                value: 0,
                color: '#cc00cc',
              },
              {
                value: 1,
                color: '#0066cc',
              },
              {
                value: 2,
                color: '#009933',
              },
              {
                value: 5,
                color: '#ffff00',
              },
              {
                value: 10,
                color: '#ff0000',
              },
              {
                value: 20,
                color: '#ffcccc',
              },
            ],
          },
          unit: 'm',
          hasSetting: false,
        },
        {
          name: 'SSC',
          longName: 'Sea State Code',
          models: [
            {
              category: 'Wave',
              field: 'SSC',
              modelDir: 'GFS',
              btnText: 'GFS',
              longName:
                'In oceanography, sea state is the general condition of the free surface on a large body of water, with respect to wind waves and swell, at a certain location and moment.',
              link: 'https://en.wikipedia.org/wiki/Sea_state',
              region: 'G',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
          ],
          colorbar: {
            hasColorbar: true,
            step: 1,
            minOrg: 0,
            colormapOrg: [
              {
                value: 0,
                color: '#cc00cc',
              },
              {
                value: 1,
                color: '#9966ff',
              },
              {
                value: 2,
                color: '#3366ff',
              },
              {
                value: 3,
                color: '#0099ff',
              },
              {
                value: 4,
                color: '#00cc66',
              },
              {
                value: 5,
                color: '#66ff33',
              },
              {
                value: 6,
                color: '#ffff00',
              },
              {
                value: 7,
                color: '#ff6600',
              },
              {
                value: 8,
                color: '#cc0000',
              },
              {
                value: 9,
                color: '#ffcccc',
              },
            ],
            colormap: [
              {
                value: 0,
                color: '#cc00cc',
              },
              {
                value: 1,
                color: '#9966ff',
              },
              {
                value: 2,
                color: '#3366ff',
              },
              {
                value: 3,
                color: '#0099ff',
              },
              {
                value: 4,
                color: '#00cc66',
              },
              {
                value: 5,
                color: '#66ff33',
              },
              {
                value: 6,
                color: '#ffff00',
              },
              {
                value: 7,
                color: '#ff6600',
              },
              {
                value: 8,
                color: '#cc0000',
              },
              {
                value: 9,
                color: '#ffcccc',
              },
            ],
          },
          unit: '',
          hasSetting: false,
        },
      ],
    },
    {
      name: 'SHF',
      show: true,
      atmosphere: false,
      longName: 'Surface Heat Flux',
      fields: [
        {
          name: 'SHF',
          models: [
            {
              category: 'SHF',
              field: 'SHF',
              subProducts: { hasSub: false },
              modelDir: 'HYCOM',
              btnText: 'HYCOM',
              longName: 'Hybrid Coordinate Ocean Model',
              link: 'https://www.hycom.org/',
              region: 'G',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
          ],
          colorbar: {
            hasColorbar: true,
            step: 1,
            minOrg: -2000,
            colormapOrg: [
              {
                value: -1500,
                color: '#ff00ff',
              },
              {
                value: -1000,
                color: '#0099ff',
              },
              {
                value: -500,
                color: '#33cc33',
              },
              {
                value: 0,
                color: '#ffffff',
              },
              {
                value: 500,
                color: '#ffff00',
              },
              {
                value: 1000,
                color: '#ff6600',
              },
              {
                value: 1500,
                color: '#ff0000',
              },
            ],
            colormap: [
              {
                value: -1500,
                color: '#ff00ff',
              },
              {
                value: -1000,
                color: '#0099ff',
              },
              {
                value: -500,
                color: '#33cc33',
              },
              {
                value: 0,
                color: '#ffffff',
              },
              {
                value: 500,
                color: '#ffff00',
              },
              {
                value: 1000,
                color: '#ff6600',
              },
              {
                value: 1500,
                color: '#ff0000',
              },
            ],
          },
          unit: '<sup>w</sup>&frasl;<sub>m<sup>2</sup></sub>',
          hasSetting: false,
        },
      ],
    },
    {
      name: 'Seaice',
      show: true,
      atmosphere: false,
      longName: null,
      fields: [
        {
          name: 'Seaice',
          models: [
            // {
            //   field: 'Seaice',
            //   modelDir: 'CMC',
            //   btnText: 'GEM',
            //   longName: 'Global Environmental Multiscale Model',
            //   depthProperties: {
            //     hasDepth: false
            //   },
            //   imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
            //   imgBndsZoomed: false,
            //   min: 0,
            //   max: 100,
            //   availDateTimes: [],
            //   hasDateTime: true,
            //   colorbar: {
            //     hasColorbar: true,
            //     labels: [
            //       { location: 0, label: '100' },
            //       { location: 0.2, label: '80' },
            //       { location: 0.4, label: '60' },
            //       { location: 0.6, label: '40' },
            //       { location: 0.8, label: '20' },
            //       { location: 1, label: '0' }
            //     ],
            //     colormap: [
            //       {
            //         minValue: 0,
            //         maxValue: 100,
            //         // minColor: [255, 255, 255],
            //         // maxColor: [0, 51, 153]
            //         minColor: [102,179,255],
            //         maxColor: [0,51,102]
            //       }
            //     ]
            //   },
            //   unit: '%'
            // },
            {
              category: 'Seaice',
              field: 'Seaice',
              subProducts: { hasSub: false },
              modelDir: 'RTOFS',
              btnText: 'RTOFS',
              longName: 'Real-Time Ocean Forecast System',
              link: 'https://polar.ncep.noaa.gov/global/',
              region: 'G',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
            {
              category: 'Seaice',
              field: 'Seaice',
              subProducts: { hasSub: false },
              modelDir: 'RIOPS',
              btnText: 'RIOPS',
              longName: 'Regional Ice Ocean Prediction System',
              link: 'https://eccc-msc.github.io/open-data/msc-data/nwp_riops/readme_riops-datamart-alpha_en/',
              region: 'R',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
            {
              category: 'Seaice',
              field: 'Seaice',
              subProducts: { hasSub: false },
              modelDir: 'Coraltemp',
              btnText: 'Coraltemp',
              longName:
                'Daily Global 5km Satellite Coral Bleaching Heat Stress Monitoring (v3.1)',
              link: 'https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.nodc:CRW-5km-HeatStressProducts',
              region: 'G',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
            {
              category: 'Seaice',
              field: 'Seaice',
              subProducts: { hasSub: false },
              modelDir: 'Barents',
              btnText: 'Barents',
              longName: '',
              link: 'https://www.met.no/hav-og-nordomrader-landing',
              region: 'R',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
          ],
          colorbar: {
            hasColorbar: true,
            minOrg: 0,
            step: 1,
            toFixed: 0,
            colormapOrg: [
              {
                value: 0,
                color: '#66b3ff',
              },
              {
                value: 100,
                color: '#003366',
              },
            ],
            colormap: [
              {
                value: 0,
                color: '#66b3ff',
              },
              {
                value: 100,
                color: '#003366',
              },
            ],
          },
          unit: '%',
          icon: 'mdi-skate',
          hasSetting: false,
        },
      ],
    },
    {
      name: 'Chlorophyll',
      show: true,
      atmosphere: false,
      longName: null,
      fields: [
        {
          name: 'Chlorophyll',
          models: [
            {
              category: 'Chlorophyll',
              field: 'Chlorophyll',
              subProducts: { hasSub: false },
              modelDir: 'MODIS',
              btnText: 'MODIS',
              longName: 'Moderate Resolution Imaging Spectroradiometer',
              link: 'https://modis.gsfc.nasa.gov/data/dataprod/chlor_a.php',
              region: 'G',
              depthProperties: {
                hasDepth: false,
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
          ],
          colorbar: {
            hasColorbar: true,
            step: 0.01,
            minOrg: -3,
            toFixed: 0,
            colormapOrg: [
              {
                value: -2,
                color: '#003300',
              },
              {
                value: -1,
                color: '#99ff99',
              },
              {
                value: 0,
                color: '#ffff00',
              },
              {
                value: 1,
                color: '#ff9933',
              },
              {
                value: 2,
                color: '#ff0000',
              },
              {
                value: 3,
                color: '#ffcccc',
              },
            ],
            colormap: [
              {
                value: -2,
                color: '#003300',
              },
              {
                value: -1,
                color: '#99ff99',
              },
              {
                value: 0,
                color: '#ffff00',
              },
              {
                value: 1,
                color: '#ff9933',
              },
              {
                value: 2,
                color: '#ff0000',
              },
              {
                value: 3,
                color: '#ffcccc',
              },
            ],
          },
          unit: 'log <sup>mg</sup>&frasl;<sub>m<sup>3</sup></sub>',
          icon: 'mdi-bacteria',
          hasSetting: false,
        },
      ],
    },
    // {
    //   name: 'Altimetry',
    //   show: false,
    //   longName: null,
    //   fields: [
    //     {
    //       name: 'Altimetry',
    //       models: [],
    //       colorbar: {
    //         hasColorbar: true,
    //         step: 0.001,
    //         minOrg: -1,
    //         toFixed: 3,
    //         colormapOrg: [
    //           {
    //             value: -1,
    //             color: '#003399',
    //           },
    //           {
    //             value: -0.75,
    //             color: '#33cccc',
    //           },
    //           {
    //             value: -0.5,
    //             color: '#00cc66',
    //           },
    //           {
    //             value: -0.25,
    //             color: '#66ff66',
    //           },
    //           {
    //             value: 0,
    //             color: '#ffffff',
    //           },
    //           {
    //             value: 0.25,
    //             color: '#ffff00',
    //           },
    //           {
    //             value: 0.5,
    //             color: '#ff9900',
    //           },
    //           {
    //             value: 0.75,
    //             color: '#ff3300',
    //           },
    //           {
    //             value: 1,
    //             color: '#800000',
    //           },
    //         ],
    //         colormap: [
    //           {
    //             value: -1,
    //             color: '#003399',
    //           },
    //           {
    //             value: -0.75,
    //             color: '#33cccc',
    //           },
    //           {
    //             value: -0.5,
    //             color: '#00cc66',
    //           },
    //           {
    //             value: -0.25,
    //             color: '#66ff66',
    //           },
    //           {
    //             value: 0,
    //             color: '#ffffff',
    //           },
    //           {
    //             value: 0.25,
    //             color: '#ffff00',
    //           },
    //           {
    //             value: 0.5,
    //             color: '#ff9900',
    //           },
    //           {
    //             value: 0.75,
    //             color: '#ff3300',
    //           },
    //           {
    //             value: 1,
    //             color: '#800000',
    //           },
    //         ],
    //       },
    //       unit: 'm',
    //       icon: '',
    //       hasSetting: false,
    //     },
    //   ],
    // },
    {
      name: 'temperature',
      show: true,
      atmosphere: true,
      longName: 'Air Temperature',
      fields: [
        {
          name: 'temperature',
          models: [
            {
              category: 'temperature',
              field: 'temperature',
              subProducts: { hasSub: false },
              modelDir: 'HRDPS',
              btnText: 'HRDPS',
              longName: '',
              link: '',
              region: 'R',
              depthProperties: {
                hasDepth: true,
                iDepth: 0,
                depthLabels: [
                  '1015',
                  '1000',
                  '985',
                  '970',
                  '950',
                  '925',
                  '900',
                  '875',
                  '850',
                  '800',
                  '750',
                  '700',
                  '650',
                  '600',
                  '550',
                  '500',
                  '450',
                  '400',
                  '350',
                  '300',
                  '275',
                  '250',
                  '225',
                  '200',
                  '175',
                  '150',
                  '100',
                  '50',
                  '30',
                  '20',
                  '10',
                ],
                depthValues: [
                  '1015',
                  '1000',
                  '0985',
                  '0970',
                  '0950',
                  '0925',
                  '0900',
                  '0875',
                  '0850',
                  '0800',
                  '0750',
                  '0700',
                  '0650',
                  '0600',
                  '0550',
                  '0500',
                  '0450',
                  '0400',
                  '0350',
                  '0300',
                  '0275',
                  '0250',
                  '0225',
                  '0200',
                  '0175',
                  '0150',
                  '0100',
                  '0050',
                  '0030',
                  '0020',
                  '0010',
                ],
              },
              imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
              imgBndsZoomed: false,
              availDateTimes: [],
              hasDateTime: true,
            },
          ],
          colorbar: {
            hasColorbar: true,
            step: 0.1,
            minOrg: -100,
            toFixed: 0,
            colormapOrg: [
              {
                value: -40,
                color: '#cc00cc',
              },
              {
                value: -30,
                color: '#ff99ff',
              },
              {
                value: -20,
                color: '#0066cc',
              },
              {
                value: -10,
                color: '#66ffcc',
              },
              {
                value: 0,
                color: '#009933',
              },
              {
                value: 10,
                color: '#ccff66',
              },
              {
                value: 20,
                color: '#ffff00',
              },
              {
                value: 30,
                color: '#ff9933',
              },
              {
                value: 40,
                color: '#ff0000',
              },
              {
                value: 50,
                color: '#ffcccc',
              },
            ],
            colormap: [
              {
                value: -40,
                color: '#cc00cc',
              },
              {
                value: -30,
                color: '#ff99ff',
              },
              {
                value: -20,
                color: '#0066cc',
              },
              {
                value: -10,
                color: '#66ffcc',
              },
              {
                value: 0,
                color: '#009933',
              },
              {
                value: 10,
                color: '#ccff66',
              },
              {
                value: 20,
                color: '#ffff00',
              },
              {
                value: 30,
                color: '#ff9933',
              },
              {
                value: 40,
                color: '#ff0000',
              },
              {
                value: 50,
                color: '#ffcccc',
              },
            ],
          },
          unit: '&deg;C',
          icon: 'mdi-thermometer',
          hasSetting: false,
        },
      ],
    },
    // {
    //   field: 'AIS',
    // show:true,
    //   models: [
    //     {
    //       field: 'AIS',
    //       modelDir: 'US',
    //       btnText: 'US',
    //       longName: '',
    //       depthProperties: {
    //         hasDepth: false
    //       },
    //       imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
    //       imgBndsZoomed: false,
    //       min: 0,
    //       max: 1000,
    //       availDateTimes: [],
    //       hasDateTime: true,
    //       colorbar: {
    //         hasColorbar: true,
    //         labels: [
    //           { location: 0, label: '1000+' },
    //           { location: 0.3333, label: '10' },
    //           { location: 0.6667, label: '0.1' },
    //           { location: 1, label: '0.001-' }
    //         ],
    //         colormap: [
    //           {
    //             minValue: -3,
    //             maxValue: -1,
    //             minColor: [0, 51, 0],
    //             maxColor: [153, 255, 153]
    //           },
    //           {
    //             minValue: -1,
    //             maxValue: 1,
    //             minColor: [255, 255, 0],
    //             maxColor: [255, 153, 51]
    //           },
    //           {
    //             minValue: 1,
    //             maxValue: 3,
    //             minColor: [255, 0, 0],
    //             maxColor: [255, 204, 204]
    //           }
    //         ]
    //       },
    //       unit: '<sup>mg</sup>&frasl;<sub>m<sup>3</sup></sub>'
    //     }
    //   ],
    //   icon: 'mdi-bacteria',
    //   hasSetting: false
    // },
    // {
    //   field: 'Iceberg',
    //   models: [
    //     {
    //       field: 'Iceberg',
    //       modelDir: 'NOAA',
    //       btnText: 'NOAA',
    //       longName: 'National Oceanic and Atmospheric Administration',
    //       depthProperties: {
    //         hasDepth: false
    //       },
    //       imgBnds: { minLon: -180, maxLon: 180, minLat: -80, maxLat: 80 },
    //       imgBndsZoomed: false,
    //       // minOrg: 0,
    //       // maxOrg: 1000,
    //       // min: 0,
    //       // max: 1000,
    //       availDateTimes: [],
    //       hasDateTime: false,
    //       colorbar: {
    //         hasColorbar: true,
    //         labels: [
    //           { location: 0.0416667, label: 'Jan' },
    //           { location: 0.125, label: 'Feb' },
    //           { location: 0.2083333, label: 'Mar' },
    //           { location: 0.2916667, label: 'Apr' },
    //           { location: 0.375, label: 'May' },
    //           { location: 0.4583333, label: 'Jun' },
    //           { location: 0.5416667, label: 'Jul' },
    //           { location: 0.625, label: 'Aug' },
    //           { location: 0.7083333, label: 'Sep' },
    //           { location: 0.7916667, label: 'Oct' },
    //           { location: 0.875, label: 'Nov' },
    //           { location: 0.9583333, label: 'Dec' }
    //         ],
    //         colormap: [
    //           {
    //             minValue: 12,
    //             maxValue: 12,
    //             minColor: [255, 153, 51],
    //             maxColor: [255, 153, 51]
    //           },
    //           {
    //             minValue: 11,
    //             maxValue: 11,
    //             minColor: [255, 153, 0],
    //             maxColor: [255, 153, 0]
    //           },
    //           {
    //             minValue: 10,
    //             maxValue: 10,
    //             minColor: [204, 102, 0],
    //             maxColor: [204, 102, 0]
    //           },
    //           {
    //             minValue: 9,
    //             maxValue: 9,
    //             minColor: [51, 204, 51],
    //             maxColor: [51, 204, 51]
    //           },
    //           {
    //             minValue: 8,
    //             maxValue: 8,
    //             minColor: [0, 204, 0],
    //             maxColor: [0, 204, 0]
    //           },
    //           {
    //             minValue: 7,
    //             maxValue: 7,
    //             minColor: [0, 153, 0],
    //             maxColor: [0, 153, 0]
    //           },
    //           {
    //             minValue: 6,
    //             maxValue: 6,
    //             minColor: [255, 102, 204],
    //             maxColor: [255, 102, 204]
    //           },
    //           {
    //             minValue: 5,
    //             maxValue: 5,
    //             minColor: [255, 51, 153],
    //             maxColor: [255, 51, 153]
    //           },
    //           {
    //             minValue: 4,
    //             maxValue: 4,
    //             minColor: [255, 51, 204],
    //             maxColor: [255, 51, 204]
    //           },
    //           {
    //             minValue: 3,
    //             maxValue: 3,
    //             minColor: [0, 153, 255],
    //             maxColor: [0, 153, 255]
    //           },
    //           {
    //             minValue: 2,
    //             maxValue: 2,
    //             minColor: [0, 102, 204],
    //             maxColor: [0, 102, 204]
    //           },
    //           {
    //             minValue: 1,
    //             maxValue: 1,
    //             minColor: [0, 51, 204],
    //             maxColor: [0, 51, 204]
    //           }
    //         ]
    //       }
    //       // unit: ""
    //     }
    //   ],
    //   icon: 'mdi-triangle',
    //   hasSetting: true
    // }
  ],

  NOAAbathymetries: [
    {
      region: 'adak_1_mhw_2009',
      latMin: 51.25,
      latMax: 52.16,
      lonMin: -177.24,
      lonMax: -175.78,
      n: 18,
      min: -4390,
      max: 0,
    },
    {
      region: 'akutan_83_mhhw_2009',
      latMin: 53.61,
      latMax: 54.39,
      lonMin: 193.11,
      lonMax: 194.93,
      n: 6,
      min: -1525,
      max: 0,
    },
    {
      region: 'akutan_8_mhhw_2009',
      latMin: 52.55,
      latMax: 54.41,
      lonMin: 190.37,
      lonMax: 195.03,
      n: 28,
      min: -7074,
      max: 0,
    },
    {
      region: 'arecibo_13_mhw_2007',
      latMin: 18.35,
      latMax: 18.8,
      lonMin: -67.1,
      lonMax: -66.5,
      n: 15,
      min: -3660,
      max: 0,
    },
    {
      region: 'arena_cove_13_mhw_2009',
      latMin: 38.4,
      latMax: 39.4,
      lonMin: -124.43,
      lonMax: -123.43,
      n: 15,
      min: -3753,
      max: 0,
    },
    {
      region: 'atka_1_mhw_2010',
      latMin: 51.59,
      latMax: 52.49,
      lonMin: -175.78,
      lonMax: -172.9,
      n: 18,
      min: -4597,
      max: 0,
    },
    {
      region: 'atka_815_mhhw_2017',
      latMin: 52.071,
      latMax: 52.299,
      lonMin: -174.259,
      lonMax: -174.001,
      n: 7,
      min: -172,
      max: 0,
    },
    {
      region: 'atlantic_city_13_mhw_2007',
      latMin: 38.85,
      latMax: 39.75,
      lonMin: -75.05,
      lonMax: -74.0,
      n: 2,
      min: -49,
      max: 0,
    },
    {
      region: 'bar_harbor_13_navd88_2011',
      latMin: 43.69,
      latMax: 44.69,
      lonMin: -68.7,
      lonMax: -67.63,
      n: 2,
      min: -260,
      max: 0,
    },
    {
      region: 'bermuda_1_msl_2013',
      latMin: 32.17,
      latMax: 32.55,
      lonMin: -65.06,
      lonMax: -64.51,
      n: 16,
      min: -3906,
      max: 0,
    },
    {
      region: 'bermuda_3_msl_2013',
      latMin: 31.5,
      latMax: 33.0,
      lonMin: -65.5,
      lonMax: -64.0,
      n: 20,
      min: -4920,
      max: 0,
    },
    {
      region: 'biloxi_13_mhw_2007',
      latMin: 29.7,
      latMax: 30.6,
      lonMin: -89.3,
      lonMax: -88.3,
      n: 2,
      min: -41,
      max: 0,
    },
    {
      region: 'british_columbia_3_msl_2013',
      latMin: 48.05,
      latMax: 54.2,
      lonMin: -137.45,
      lonMax: -122.2,
      n: 17,
      min: -4266,
      max: 0,
    },
    {
      region: 'cape_hatteras_13_mhw_2006',
      latMin: 34.75,
      latMax: 35.8,
      lonMin: -76.05,
      lonMax: -75.05,
      n: 12,
      min: -2879,
      max: 0,
    },
    {
      region: 'central_california_1_navd88_2010',
      latMin: 37.0,
      latMax: 38.75,
      lonMin: -124.0,
      lonMax: -121.85,
      n: 16,
      min: -3884,
      max: 0,
    },
    {
      region: 'central_florida_13_navd88_2014',
      latMin: 27.27,
      latMax: 28.88,
      lonMin: -80.88,
      lonMax: -79.95,
      n: 2,
      min: -296,
      max: 0,
    },
    {
      region: 'central_oregon_13_navd88_2015',
      latMin: 43.7,
      latMax: 45.14,
      lonMin: -124.63,
      lonMax: -123.81,
      n: 2,
      min: -496,
      max: 0,
    },
    {
      region: 'chenega_815_mhhw_2011',
      latMin: 59.97,
      latMax: 60.19,
      lonMin: -148.17,
      lonMax: -147.89,
      n: 2,
      min: -425,
      max: 0,
    },
    {
      region: 'chignik_13_mhhw_2014',
      latMin: 56.28,
      latMax: 56.36,
      lonMin: -158.58,
      lonMax: -158.34,
      n: 3,
      min: -73,
      max: 0,
    },
    {
      region: 'chignik_1_mhhw_2014',
      latMin: 55.52,
      latMax: 56.44,
      lonMin: -159.58,
      lonMax: -157.98,
      n: 2,
      min: -309,
      max: 0,
    },
    {
      region: 'chiniak_815_mhhw_2015',
      latMin: 57.6,
      latMax: 57.65,
      lonMin: -152.38,
      lonMax: -152.18,
      n: 4,
      min: -85,
      max: 0,
    },
    {
      region: 'cold_bay_815_mhhw_2013',
      latMin: 55.14,
      latMax: 55.26,
      lonMin: -162.78,
      lonMax: -162.58,
      n: 3,
      min: -72,
      max: 0,
    },
    {
      region: 'cold_bay_83_mhhw_2013',
      latMin: 54.7,
      latMax: 55.7,
      lonMin: -163.1,
      lonMax: -162.1,
      n: 6,
      min: -150,
      max: 0,
    },
    {
      region: 'cold_bay_8_mhhw_2013',
      latMin: 53.0,
      latMax: 56.0,
      lonMin: -164.5,
      lonMax: -161.5,
      n: 30,
      min: -7526,
      max: 0,
    },
    {
      region: 'cordova_13_mhw_2010',
      latMin: 60.49,
      latMax: 60.82,
      lonMin: -146.77,
      lonMax: -145.21,
      n: 2,
      min: -411,
      max: 0,
    },
    {
      region: 'cordova_3_mhw_2010',
      latMin: 59.75,
      latMax: 60.82,
      lonMin: -146.77,
      lonMax: -145.21,
      n: 2,
      min: -408,
      max: 0,
    },
    {
      region: 'cordova_815_mhhw_2009',
      latMin: 60.49,
      latMax: 60.75,
      lonMin: 214.07,
      lonMax: 214.51,
    },
    {
      region: 'corpus_christi_13_mhw_2007',
      latMin: 27.3,
      latMax: 28.15,
      lonMin: -97.7,
      lonMax: -96.65,
      n: 3,
      min: -76,
      max: 0,
    },
    {
      region: 'craig_13_mhw_2012',
      latMin: 55.04,
      latMax: 55.81,
      lonMin: -133.91,
      lonMax: -132.88,
      n: 2,
      min: -407,
      max: 0,
    },
    {
      region: 'crescent_city_13_navd88_2010',
      latMin: 41.42,
      latMax: 42.53,
      lonMin: -125.25,
      lonMax: -123.88,
      n: 13,
      min: -3188,
      max: 0,
    },
    {
      region: 'daytona_beach_13_mhw_2007',
      latMin: 28.85,
      latMax: 29.7,
      lonMin: -81.4,
      lonMax: -80.5,
      n: 2,
      min: -37,
      max: 0,
    },
    {
      region: 'destin_13_navd88_2016',
      latMin: 30.0,
      latMax: 30.53,
      lonMin: -86.8,
      lonMax: -86.07,
      n: 5,
      min: -118,
      max: 0,
    },
    {
      region: 'dutch_harbor_1_mhw_2006',
      latMin: 53.5,
      latMax: 54.35,
      lonMin: -167.2,
      lonMax: -165.9,
      n: 7,
      min: -1748,
      max: 0,
    },
    {
      region: 'easter_island_3_isl_2016',
      latMin: -28.5,
      latMax: -25.8,
      lonMin: -111.2,
      lonMax: -107.5,
      n: 16,
      min: -4064,
      max: 0,
    },
    {
      region: 'eastern_canada_3_isl_2015',
      latMin: 41.0,
      latMax: 52.0,
      lonMin: -71.0,
      lonMax: -42.0,
    },
    {
      region: 'elfin_cove_13_mhhw_2012',
      latMin: 58.1,
      latMax: 58.27,
      lonMin: -136.47,
      lonMax: -136.26,
      n: 2,
      min: -334,
      max: 0,
    },
    {
      region: 'elfin_cove_13_mhw_2011',
      latMin: 57.53,
      latMax: 58.67,
      lonMin: -137.27,
      lonMax: -135.97,
      n: 9,
      min: -2234,
      max: 0,
    },
    {
      region: 'eureka_13_navd88_2009',
      latMin: 40.27,
      latMax: 41.42,
      lonMin: -125.01,
      lonMax: -124.0,
      n: 12,
      min: -3070,
      max: 0,
    },
    {
      region: 'fajardo_13_mhw_2007',
      latMin: 18.05,
      latMax: 18.6,
      lonMin: -65.9,
      lonMax: -65.35,
      n: 5,
      min: -1272,
      max: 0,
    },
    {
      region: 'false_pass_815_mhhw_2016',
      latMin: 54.78,
      latMax: 54.9,
      lonMin: -163.47,
      lonMax: -163.25,
      n: 7,
      min: -172,
      max: 0,
    },
    {
      region: 'fort_bragg_13_navd88_2012',
      latMin: 39.38,
      latMax: 40.28,
      lonMin: -125.05,
      lonMax: -123.72,
      n: 13,
      min: -3197,
      max: 0,
    },
    {
      region: 'galapagos_1_isl_2016',
      latMin: -1.98,
      latMax: 1.95,
      lonMin: -92.32,
      lonMax: -87.2,
      n: 16,
      min: -3982,
      max: 0,
    },
    {
      region: 'galveston_13_mhw_2007',
      latMin: 28.85,
      latMax: 29.8,
      lonMin: -95.25,
      lonMax: -94.3,
      n: 2,
      min: -26,
      max: 0,
    },
    {
      region: 'garibaldi_13_navd88_2013',
      latMin: 45.1,
      latMax: 45.9,
      lonMin: -124.5,
      lonMax: -123.7,
      n: 2,
      min: -462,
      max: 0,
    },
    {
      region: 'grenada_1_isl_2017',
      latMin: 11.7,
      latMax: 13.5,
      lonMin: -62.3,
      lonMax: -61.0,
      n: 12,
      min: -3058,
      max: 0,
    },
    {
      region: 'guayama_13_mhw_2007',
      latMin: 17.7,
      latMax: 18.05,
      lonMin: -66.4,
      lonMax: -65.7,
      n: 9,
      min: -2183,
      max: 0,
    },
    {
      region: 'gustavus_815_mhhw_2012',
      latMin: 58.33,
      latMax: 58.49,
      lonMin: -135.97,
      lonMax: -135.54,
      n: 5,
      min: -126,
      max: 0,
    },
    {
      region: 'hanalei_13_mhw_2011',
      latMin: 22.09,
      latMax: 22.66,
      lonMin: -159.91,
      lonMax: -159.09,
      n: 18,
      min: -4596,
      max: 0,
    },
    {
      region: 'hilo_13_mhw_2011',
      latMin: 19.17,
      latMax: 20.26,
      lonMin: -155.47,
      lonMax: -154.46,
      n: 22,
      min: -5627,
      max: 0,
    },
    {
      region: 'hoonah_815_mhhw_2012',
      latMin: 58.07,
      latMax: 58.17,
      lonMin: -135.51,
      lonMax: -135.38,
      n: 7,
      min: -178,
      max: 0,
    },
    {
      region: 'juneau_815_mhhw_2010',
      latMin: 58.03,
      latMax: 58.91,
      lonMin: -135.23,
      lonMax: -133.91,
      n: 3,
      min: -696,
      max: 0,
    },
    {
      region: 'kachemak_bay_13_mhw_2010',
      latMin: 59.32,
      latMax: 59.82,
      lonMin: -152.1,
      lonMax: -150.89,
      n: 7,
      min: -175,
      max: 0,
    },
    {
      region: 'kaneohe_13_mhw_2016',
      latMin: 21.31,
      latMax: 21.51,
      lonMin: -157.835,
      lonMax: -157.649,
      n: 4,
      min: -944,
      max: 0,
    },
    {
      region: 'kauai_13_mhw_2012',
      latMin: 21.55,
      latMax: 22.4,
      lonMin: -160.4,
      lonMax: -159.09,
      n: 18,
      min: -4604,
      max: 0,
    },
    {
      region: 'kawaihae_13_mhw_2011',
      latMin: 19.87,
      latMax: 20.45,
      lonMin: -156.37,
      lonMax: -155.37,
      n: 17,
      min: -4170,
      max: 0,
    },
    {
      region: 'keauhou_13_mhw_2011',
      latMin: 19.22,
      latMax: 19.92,
      lonMin: -156.31,
      lonMax: -155.75,
      n: 19,
      min: -4814,
      max: 0,
    },
    {
      region: 'key_west_13_navd88_2011',
      latMin: 23.98,
      latMax: 25.02,
      lonMin: -82.18,
      lonMax: -81.27,
      n: 5,
      min: -1188,
      max: 0,
    },
    {
      region: 'king_cove_815_mhhw_2013',
      latMin: 55.0,
      latMax: 55.1,
      lonMin: -162.38,
      lonMax: -162.24,
      n: 6,
      min: -146,
      max: 0,
    },
    {
      region: 'king_cove_83_mhhw_2013',
      latMin: 54.58,
      latMax: 55.34,
      lonMin: -162.8,
      lonMax: -161.84,
      n: 7,
      min: -175,
      max: 0,
    },
    {
      region: 'king_cove_8_mhhw_2013',
      latMin: 54.24,
      latMax: 55.5,
      lonMin: -163.8,
      lonMax: -161.8,
      n: 8,
      min: -184,
      max: 0,
    },
    {
      region: 'kodiak_13_mhw_2013',
      latMin: 57.58,
      latMax: 58.0,
      lonMin: -152.8,
      lonMax: -152.0,
      n: 2,
      min: -387,
      max: 0,
    },
    {
      region: 'lahaina_13_mhw_2007',
      latMin: 20.7,
      latMax: 21.1,
      lonMin: -156.9,
      lonMax: -156.55,
      n: 2,
      min: -445,
      max: 0,
    },
    {
      region: 'larsen_bay_815_mhhw_2016',
      latMin: 57.51,
      latMax: 57.59,
      lonMin: -154.15,
      lonMax: -153.9,
      n: 7,
      min: -165,
      max: 0,
    },
    {
      region: 'mariana_trh_6_msl_2012',
      latMin: 10.0,
      latMax: 21.998,
      lonMin: 139.0,
      lonMax: 149.998,
      n: 43,
      min: -10955,
      max: 0,
    },
    {
      region: 'marquesas_islands_3_isl_2017',
      latMin: -11.4,
      latMax: -7.15,
      lonMin: -142.3,
      lonMax: -136.9,
      n: 20,
      min: -5004,
      max: 0,
    },
    {
      region: 'mayaguez_13_mhw_2006',
      latMin: 17.9,
      latMax: 18.6,
      lonMin: -67.6,
      lonMax: -67.1,
      n: 15,
      min: -3750,
      max: 0,
    },
    {
      region: 'mayaguez_13_mhw_2007',
      latMin: 17.9,
      latMax: 18.6,
      lonMin: -67.6,
      lonMax: -67.1,
      n: 15,
      min: -3631,
      max: 0,
    },
    {
      region: 'midway_island_13_mhw_2012',
      latMin: 28.09,
      latMax: 28.42,
      lonMin: -177.57,
      lonMax: -177.16,
      n: 16,
      min: -3866,
      max: 0,
    },
    {
      region: 'midway_island_3_mhw_2012',
      latMin: 27.77,
      latMax: 28.7,
      lonMin: -177.88,
      lonMax: -176.87,
    },
    {
      region: 'mobile_13_navd88_2009',
      latMin: 30.0,
      latMax: 31.0,
      lonMin: -88.3,
      lonMax: -87.65,
      n: 2,
      min: -33,
      max: 0,
    },
    {
      region: 'montauk_13_mhw_2007',
      latMin: 40.6,
      latMax: 41.4,
      lonMin: -72.6,
      lonMax: -71.5,
      n: 5,
      min: -119,
      max: 0,
    },
    {
      region: 'monterey_13_navd88_2012',
      latMin: 35.7,
      latMax: 37.2,
      lonMin: -122.42,
      lonMax: -121.28,
      n: 15,
      min: -3598,
      max: 0,
    },
    {
      region: 'morehead_city_13_navd88_2011',
      latMin: 34.37,
      latMax: 35.57,
      lonMin: -77.27,
      lonMax: -76.0,
      n: 3,
      min: -66,
      max: 0,
    },
    {
      region: 'myrtle_beach_13_mhw_2006',
      latMin: 33.25,
      latMax: 33.95,
      lonMin: -79.2,
      lonMax: -78.4,
      n: 2,
      min: -31,
      max: 0,
    },
    {
      region: 'myrtle_beach_1_mhw_2006',
      latMin: 33.25,
      latMax: 33.95,
      lonMin: -79.2,
      lonMax: -78.4,
      n: 2,
      min: -31,
      max: 0,
    },
    {
      region: 'nantucket_13_mhw_2008',
      latMin: 40.81,
      latMax: 41.71,
      lonMin: -70.67,
      lonMax: -69.49,
      n: 6,
      min: -153,
      max: 0,
    },
    {
      region: 'new_orleans_13_navd88_2010',
      latMin: 29.7,
      latMax: 30.5,
      lonMin: -90.65,
      lonMax: -89.3,
      n: 3,
      min: -69,
      max: 0,
    },
    {
      region: 'nikolski_13_mhhw_2014',
      latMin: 52.89,
      latMax: 53.0,
      lonMin: -168.98,
      lonMax: -168.73,
      n: 4,
      min: -96,
      max: 0,
    },
    {
      region: 'nikolski_1_mhhw_2014',
      latMin: 52.29,
      latMax: 53.19,
      lonMin: -169.66,
      lonMax: -168.09,
      n: 16,
      min: -3892,
      max: 0,
    },
    {
      region: 'niue_3_isl_2016',
      latMin: -20.0,
      latMax: -17.5,
      lonMin: -172.85,
      lonMax: -169.2,
      n: 38,
      min: -9664,
      max: 0,
    },
    {
      region: 'northern_gulf_1_navd88_2010',
      latMin: 28.5,
      latMax: 31.25,
      lonMin: -90.75,
      lonMax: -85.0,
      n: 11,
      min: -2564,
      max: 0,
    },
    {
      region: 'oahu_13_mhw_2011',
      latMin: 21.02,
      latMax: 22.06,
      lonMin: -158.45,
      lonMax: -157.45,
      n: 20,
      min: -4976,
      max: 0,
    },
    {
      region: 'ocean_city_13_mhw_2009',
      latMin: 37.68,
      latMax: 38.87,
      lonMin: -75.58,
      lonMax: -74.71,
      n: 3,
      min: -52,
      max: 0,
    },
    {
      region: 'ouzinkie_815_mhhw_2015',
      latMin: 57.89,
      latMax: 57.94,
      lonMin: -152.54,
      lonMax: -152.47,
      n: 5,
      min: -116,
      max: 0,
    },
    {
      region: 'pago_pago_13_mhw_2009',
      latMin: -14.4,
      latMax: -14.18,
      lonMin: -170.95,
      lonMax: -170.45,
      n: 14,
      min: -3384,
      max: 0,
    },
    {
      region: 'palm_beach_13_navd88_2010',
      latMin: 26.29,
      latMax: 27.31,
      lonMin: -80.36,
      lonMax: -79.42,
      n: 4,
      min: -797,
      max: 0,
    },
    {
      region: 'panama_city_13_navd88_2010',
      latMin: 29.55,
      latMax: 30.5,
      lonMin: -86.1,
      lonMax: -85.2,
      n: 4,
      min: -78,
      max: 0,
    },
    {
      region: 'perryville_ivanof_bay_13_mhhw_2014',
      latMin: 55.7,
      latMax: 56.0,
      lonMin: -159.58,
      lonMax: -159.0,
      n: 6,
      min: -151,
      max: 0,
    },
    {
      region: 'pe_13_mhw_2007', // ponce_13_mhw_2007
      latMin: 17.7,
      latMax: 18.05,
      lonMin: -67.1,
      lonMax: -66.4,
      n: 12,
      min: -2970,
      max: 0,
    },
    {
      region: 'port_alberni_13_navd88_2016',
      latMin: 48.95,
      latMax: 49.28,
      lonMin: -124.9,
      lonMax: -124.78,
      n: 2,
      min: -361,
      max: 0,
    },
    {
      region: 'port_alexander_13_mhw_2011',
      latMin: 55.53,
      latMax: 56.71,
      lonMin: -135.35,
      lonMax: -134.03,
      n: 10,
      min: -2394,
      max: 0,
    },
    {
      region: 'portland_13_mhw_2008',
      latMin: 43.0,
      latMax: 43.99,
      lonMin: -70.74,
      lonMax: -69.63,
      n: 10,
      min: -253,
      max: 0,
    },
    {
      region: 'port_lions_815_mhhw_2016',
      latMin: 57.84,
      latMax: 57.9,
      lonMin: -152.92,
      lonMax: -152.82,
      n: 2,
      min: -43,
      max: 0,
    },
    {
      region: 'port_orford_13_mhw_2008',
      latMin: 42.53,
      latMax: 43.73,
      lonMin: -124.97,
      lonMax: -124.13,
      n: 7,
      min: -1746,
      max: 0,
    },
    {
      region: 'port_san_luis_13_navd88_2011',
      latMin: 34.6,
      latMax: 35.7,
      lonMin: -121.3,
      lonMax: -120.45,
      n: 4,
      min: -903,
      max: 0,
    },
    {
      region: 'port_townsend_13_navd88_2011',
      latMin: 47.91,
      latMax: 48.79,
      lonMin: -123.62,
      lonMax: -122.2,
      n: 2,
      min: -361,
      max: 0,
    },
    {
      region: 'pre_william_sound_83_mhhw_2009',
      latMin: 59.65,
      latMax: 61.35,
      lonMin: 211.23,
      lonMax: 214.67,
      n: 3,
      min: -768,
      max: 0,
    },
    {
      region: 'pre_william_sound_8_mhhw_2009',
      latMin: 58.49,
      latMax: 61.51,
      lonMin: 210.99,
      lonMax: 215.01,
      n: 19,
      min: -4775,
      max: 0,
    },
    {
      region: 'puget_sound_13_navd88_2014',
      latMin: 47.01,
      latMax: 48.19,
      lonMin: -123.18,
      lonMax: -122.16,
      n: 2,
      min: -299,
      max: 0,
    },
    {
      region: 'rarotonga_1_isl_2016',
      latMin: -21.87,
      latMax: -20.68,
      lonMin: -160.42,
      lonMax: -159.08,
      n: 20,
      min: -5059,
      max: 0,
    },
    {
      region: 'san_diego_13_navd88_2012',
      latMin: 32.45,
      latMax: 33.6,
      lonMin: -117.83,
      lonMax: -117.0,
      n: 7,
      min: -1594,
      max: 0,
    },
    {
      region: 'sand_point_13_mhw_2012',
      latMin: 54.7,
      latMax: 55.7,
      lonMin: -160.9,
      lonMax: -159.17,
      n: 10,
      min: -255,
      max: 0,
    },
    {
      region: 'san_frisco_13_navd88_2010',
      latMin: 37.32,
      latMax: 38.48,
      lonMin: -123.3,
      lonMax: -121.85,
      n: 9,
      min: -2170,
      max: 0,
    },
    {
      region: 'san_juan_19_prvd02_2015',
      latMin: 18.38,
      latMax: 18.54,
      lonMin: -66.23,
      lonMax: -65.91,
      n: 4,
      min: -907,
      max: 0,
    },
    {
      region: 'santa_barbara_13_mhw_2008',
      latMin: 33.77,
      latMax: 34.62,
      lonMin: -120.51,
      lonMax: -119.14,
      n: 8,
      min: -1940,
      max: 0,
    },
    {
      region: 'santa_monica_13_navd88_2010',
      latMin: 33.2,
      latMax: 34.2,
      lonMin: -119.14,
      lonMax: -117.8,
      n: 6,
      min: -1458,
      max: 0,
    },
    {
      region: 'savannah_13_mhw_2006',
      latMin: 31.5,
      latMax: 32.45,
      lonMin: -81.35,
      lonMax: -80.35,
      n: 2,
      min: -38,
      max: 0,
    },
    {
      region: 'shemya_1_mhw_2009',
      latMin: 52.27,
      latMax: 53.06,
      lonMin: 172.45,
      lonMax: 174.21,
      n: 16,
      min: -4094,
      max: 0,
    },
    {
      region: 'sitka_13_mhw_2011',
      latMin: 56.78,
      latMax: 57.27,
      lonMin: -135.83,
      lonMax: -135.08,
      n: 2,
      min: -287,
      max: 0,
    },
    {
      region: 'sitka_3_mhw_2011',
      latMin: 56.67,
      latMax: 57.56,
      lonMin: -136.71,
      lonMax: -135.05,
      n: 9,
      min: -2297,
      max: 0,
    },
    {
      region: 'society_islands_3_isl_2016',
      latMin: -19.05,
      latMax: -15.55,
      lonMin: -153.05,
      lonMax: -147.45,
      n: 20,
      min: -5032,
      max: 0,
    },
    {
      region: 'society_islands_leeward_1_isl_2016',
      latMin: -17.1,
      latMax: -16.35,
      lonMin: -151.95,
      lonMax: -150.75,
      n: 16,
      min: -3894,
      max: 0,
    },
    {
      region: 'society_islands_windward_1_isl_2016',
      latMin: -18.05,
      latMax: -17.2,
      lonMin: -150.1,
      lonMax: -148.85,
      n: 16,
      min: -3897,
      max: 0,
    },
    {
      region: 'southeast_alaska_83_mhhw_2010',
      latMin: 54.59,
      latMax: 59.61,
      lonMin: -137.51,
      lonMax: -129.49,
      n: 13,
      min: -3223,
      max: 0,
    },
    {
      region: 'southeast_alaska_8_mhhw_2010',
      latMin: 54.19,
      latMax: 60.01,
      lonMin: -138.21,
      lonMax: -129.19,
      n: 14,
      min: -3465,
      max: 0,
    },
    {
      region: 'south_padre_island_13_navd88_2012',
      latMin: 25.82,
      latMax: 26.86,
      lonMin: -97.65,
      lonMax: -96.8,
      n: 3,
      min: -67,
      max: 0,
    },
    {
      region: 'st_croix_13_mhw_2014',
      latMin: 17.61,
      latMax: 17.88,
      lonMin: -65.04,
      lonMax: -64.4,
      n: 18,
      min: -4595,
      max: 0,
    },
    {
      region: 'st_thomas_st_john_13_mhw_2014',
      latMin: 18.17,
      latMax: 18.48,
      lonMin: -65.15,
      lonMax: -64.64,
      n: 7,
      min: -1701,
      max: 0,
    },
    {
      region: 'taholah_13_mhw_2009',
      latMin: 46.99,
      latMax: 47.65,
      lonMin: -125.3,
      lonMax: -123.7,
      n: 8,
      min: -1874,
      max: 0,
    },
    {
      region: 'tampa_bay_13_navd88_2014',
      latMin: 27.22,
      latMax: 28.26,
      lonMin: -83.41,
      lonMax: -82.37,
      n: 2,
      min: -47,
      max: 0,
    },
    {
      region: 'tatitlek_815_mhhw_2011',
      latMin: 60.81,
      latMax: 60.95,
      lonMin: -146.79,
      lonMax: -146.61,
      n: 2,
      min: -379,
      max: 0,
    },
    {
      region: 'tutuila_13_mhw_2013',
      latMin: -14.4,
      latMax: -14.18,
      lonMin: -170.95,
      lonMax: -170.45,
      n: 14,
      min: -3385,
      max: 0,
    },
    {
      region: 'unalaska_815_mhhw_2012',
      latMin: 53.8,
      latMax: 53.95,
      lonMin: -166.66,
      lonMax: -166.42,
      n: 7,
      min: -173,
      max: 0,
    },
    {
      region: 'usvi_1_mhw_2014',
      latMin: 17.0,
      latMax: 19.0,
      lonMin: -65.15,
      lonMax: -64.0,
      n: 20,
      min: -4939,
      max: 0,
    },
    {
      region: 'virginia_beach_13_mhw_2007',
      latMin: 36.45,
      latMax: 37.5,
      lonMin: -76.6,
      lonMax: -75.4,
      n: 2,
      min: -48,
      max: 0,
    },
    {
      region: 'wake_island_13_mhw_2009',
      latMin: 19.17,
      latMax: 19.4,
      lonMin: 166.47,
      lonMax: 166.82,
      n: 17,
      min: -4248,
      max: 0,
    },
    {
      region: 'wake_island_3_mhw_2009',
      latMin: 18.84,
      latMax: 19.76,
      lonMin: 166.15,
      lonMax: 167.1,
      n: 22,
      min: -5578,
      max: 0,
    },
    {
      region: 'whittier_815_mhhw_2009',
      latMin: 60.75,
      latMax: 60.85,
      lonMin: 211.25,
      lonMax: 211.51,
      n: 2,
      min: -369,
      max: 0,
    },
    {
      region: 'yakutat_815_mhhw_2009',
      latMin: 59.41,
      latMax: 59.67,
      lonMin: 220.07,
      lonMax: 220.43,
      n: 9,
      min: -217,
      max: 0,
    },
    {
      region: 'yakutat_83_mhhw_2009',
      latMin: 59.27,
      latMax: 59.91,
      lonMin: 219.53,
      lonMax: 220.63,
      n: 2,
      min: -265,
      max: 0,
    },
    {
      region: 'yakutat_8_mhhw_2009',
      latMin: 58.89,
      latMax: 60.19,
      lonMin: 219.39,
      lonMax: 221.27,
      n: 2,
      min: -344,
      max: 0,
    },
  ],

  palettes: [
    {
      name: 'thermal',
      colors: [
        '#032333',
        '#072d52',
        '#153377',
        '#32339b',
        '#50389e',
        '#664297',
        '#7a4c91',
        '#8f548c',
        '#a55c86',
        '#bb627d',
        '#d26a6f',
        '#e5745e',
        '#f4834c',
        '#fb983f',
        '#fcaf3c',
        '#f9c842',
        '#f3e14d',
        '#e8fb5b',
      ],
    },
    {
      name: 'haline',
      colors: [
        '#29186c',
        '#2e1c91',
        '#2230a3',
        '#10469a',
        '#0d5792',
        '#17658d',
        '#24728a',
        '#2e7f89',
        '#378c88',
        '#3f9a86',
        '#48a782',
        '#54b57b',
        '#66c271',
        '#80ce64',
        '#a3d75c',
        '#c6de66',
        '#e4e67e',
        '#feef9a',
      ],
    },
    {
      name: 'solar',
      colors: [
        '#331317',
        '#461a1e',
        '#591f23',
        '#6b2424',
        '#7e2a23',
        '#8e331f',
        '#9b3f1a',
        '#a74d16',
        '#b15c13',
        '#ba6c12',
        '#c27c14',
        '#ca8d17',
        '#d09e1d',
        '#d5b025',
        '#dac22d',
        '#ddd537',
        '#e0e940',
        '#e1fe4b',
      ],
    },
    {
      name: 'ice',
      colors: [
        '#030512',
        '#111228',
        '#1f1e3e',
        '#2b2a55',
        '#36356e',
        '#3c4287',
        '#3f509d',
        '#3e61ac',
        '#3f72b4',
        '#4682ba',
        '#5093c0',
        '#5da3c6',
        '#6cb2cc',
        '#7fc2d2',
        '#97d1d9',
        '#b3dfe3',
        '#cfeef0',
        '#ebfdfe',
      ],
    },
    {
      name: 'gray',
      colors: [
        '#000000',
        '#080707',
        '#171717',
        '#262525',
        '#333333',
        '#414040',
        '#4e4e4e',
        '#5c5c5b',
        '#6a6969',
        '#787877',
        '#878686',
        '#969595',
        '#a5a5a4',
        '#b6b5b4',
        '#c7c6c5',
        '#d9d8d7',
        '#ebebea',
        '#fffffe',
      ],
    },
    {
      name: 'deep',
      colors: [
        '#fefecc',
        '#dff3bb',
        '#c0e8ae',
        '#9fdda6',
        '#7fd1a3',
        '#67c4a4',
        '#59b5a4',
        '#50a5a2',
        '#4b96a0',
        '#46879c',
        '#417899',
        '#3e6996',
        '#3e5992',
        '#414988',
        '#403b71',
        '#3a3058',
        '#312541',
        '#271a2c',
      ],
    },
    {
      name: 'dense',
      colors: [
        '#e6f1f1',
        '#cde5e9',
        '#b4d8e4',
        '#9ecbe3',
        '#8bbde3',
        '#7caee4',
        '#749ee5',
        '#738de3',
        '#767bdb',
        '#7869cf',
        '#7958bf',
        '#7747ac',
        '#733896',
        '#6d2b7f',
        '#641f67',
        '#58164e',
        '#481237',
        '#360e24',
      ],
    },
    {
      name: 'algae',
      colors: [
        '#d7fad0',
        '#c4ecba',
        '#b1dfa5',
        '#9ed391',
        '#8ac77e',
        '#74bc6d',
        '#5bb15e',
        '#3da754',
        '#1e9b51',
        '#0a8e4f',
        '#07804b',
        '#0f7346',
        '#156540',
        '#185839',
        '#1a4b31',
        '#193e28',
        '#16311e',
        '#112414',
      ],
    },
    {
      name: 'rainbow',
      colors: [
        '#7f00ff',
        '#612efd',
        '#435cfa',
        '#2586f5',
        '#07abed',
        '#16cbe4',
        '#34e4d8',
        '#52f5cb',
        '#70fdbc',
        '#8efdab',
        '#acf599',
        '#cae486',
        '#e8cb71',
        '#ffab5c',
        '#ff8645',
        '#ff5c2e',
        '#ff2e17',
        '#ff0000',
      ],
    },
    {
      name: 'spectral',
      colors: [
        '#000000',
        '#7a008a',
        '#57009f',
        '#0000c5',
        '#0054dd',
        '#0095dd',
        '#00aaa8',
        '#00a667',
        '#00a600',
        '#00cf00',
        '#00f700',
        '#afff00',
        '#efe900',
        '#ffbd00',
        '#ff5100',
        '#e90000',
        '#cf0000',
        '#cccccc',
      ],
    },
  ],
})

export const mutations = {
  setSelected(state, obj) {
    if (obj === null) state.selected = null
    else
      state.selected = state.categories
        .filter((c) => c.name === obj.category)[0]
        .fields.filter((f) => f.name === obj.field)[0]
        .models.filter((model) => model.modelDir === obj.model)[0]
  },

  updateSelected(state, selected) {
    state.selected = selected
  },

  setSelectedBathymetry(state, value) {
    state.selectedBathymetry = state.bathymetries.models.filter(
      (bathymetry) => bathymetry.modelDir === value
    )[0]
  },

  setAvailDateTimes(state, obj) {
    const iCategory = state.categories.findIndex(
      (c) => c.name === obj.data.category
    )
    const iField = state.categories[iCategory].fields.findIndex(
      (f) => f.name === obj.data.field
    )
    const iModel = state.categories[iCategory].fields[iField].models.findIndex(
      (m) => m.modelDir === obj.data.model
    )
    state.categories[iCategory].fields[iField].models[iModel].availDateTimes =
      obj.availDateTimes
    state.categories[iCategory].fields[iField].models[iModel].lastProcessed =
      obj.lastProcessed
  },

  setAltimetryAvailSatDates(state, obj) {
    state.altimetryAvailSatDates = obj
  },

  setDate(state, value) {
    const dates = state.selected.availDateTimes.map((d) => d.date)
    if (dates.includes(value)) state.interDate = value
    else {
      // --- Set the next closest date to the selected one
      const futureDates = dates.filter(
        (date) => parseInt(date) >= parseInt(value)
      )
      if (futureDates.length > 0) state.interDate = futureDates[0]
      // --- If dates in future available, pick the first one (closest to now)
      else state.interDate = dates[dates.length - 1] // --- else, pick the last available date
    }
    this.commit('layers/setTime', state.interTime)

    // state.interDate = value

    // --- Check if the current selectedTime is valid
    // const times = state.selected.availDateTimes
    //   .filter(d => d.date === state.interDate)
    //   .map(d => d.time)
    // if (!times.includes(state.interTime)) this.commit('layers/setTime', times[0])
    // else this.commit('layers/setTime', state.interTime)
  },

  setTime(state, value) {
    const times = state.selected.availDateTimes
      .filter((d) => d.date === state.interDate)
      .map((d) => d.time)
    if (times.includes(value)) state.interTime = value
    else {
      // --- Set the next closest time to the selected one
      const futureTimes = times.filter(
        (time) => parseInt(time) >= parseInt(value)
      )
      if (futureTimes.length > 0) state.interTime = futureTimes[0]
      // --- If times in future available, pick the first one (closest to now)
      else state.interTime = times[times.length - 1] // --- else, pick the last available time
    }

    // if (value !== null) {
    //   state.interTime = value
    //   this.dispatch('map/redraw')
    // }
  },

  setDepth(state, i) {
    if (i === -1) i = state.selected.depthProperties.depthLabels.length - 1
    // if (state.selected.depthProperties.iDepth !== i) {
    state.selected.depthProperties.iDepth = i
    //   this.dispatch('map/redraw')
    // }
  },

  setSelectedAltimetrySatellites(state, array) {
    state.selectedAltimetrySatellites = array
  },

  setSelectedAltimetryDates(state, array) {
    state.selectedAltimetryDates = array
  },

  setSelectedAltimetryVariable(state, value) {
    state.selectedAltimetryVariable = value
  },

  setAltimetryShownGJs(state, array) {
    state.altimetryShownGJs = array
  },
  // setAltimetryGJ(state, gj) {
  //   state.altimetryGJ = gj
  // },

  setLoadingAltimetry(state, status) {
    state.loadingAltimetry = status
  },

  setColormap(state, obj) {
    state.categories.forEach((category) => {
      category.fields.forEach((field) => {
        if (field.name === obj.field.name) {
          field.colorbar.colormap = obj.colormap
        }
      })
    })
  },
}
